### ISSUE TITLE
Cant locate template for uri: 'models.py.mako'

### ISSUE THREAD

**Issue by SamuelMarks** [thomsonreuters/js2model#8]
I like the idea of your project, but can't get it to work. Example:

```bash
$ js2model -l py service.schema.json
```
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mako/lookup.py", line 247, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'models.py.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/js2model", line 28, in <module>
    exit(main())
  File "/usr/local/bin/js2model.py", line 96, in main
    generator.generate_models(files)
  File "/usr/local/lib/python3.6/site-packages/tr/jsonschema/jsonschema2model.py", line 803, in generate_models
    self.render_models()
  File "/usr/local/lib/python3.6/site-packages/tr/jsonschema/jsonschema2model.py", line 375, in render_models
    self.render_global_template(self.models.values(), global_template)
  File "/usr/local/lib/python3.6/site-packages/tr/jsonschema/jsonschema2model.py", line 427, in render_global_template
    decl_template = self.makolookup.get_template(templ_name)
  File "/usr/local/lib/python3.6/site-packages/mako/lookup.py", line 261, in get_template
    "Cant locate template for uri %r" % uri)
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'models.py.mako'
```

**Comment by jinsen47** [comment]
same on me
schema file from genson:

```json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "request": {
      "type": "object"
    },
    "response": {
      "type": "object",
      "properties": {
        "ret_code": {
          "type": "integer"
        }
      },
      "required": [
        "ret_code"
      ]
    }
  },
  "required": [
    "request",
    "response"
  ]
}
```
